#!/bin/bash

# Quick deployment script for VPK prototypes
# Deploys the latest code to production with automatic authentication handling
#
# Usage:
#   pnpm run deploy:micros          # Auto-generate version and deploy
#   pnpm run deploy:micros 1.0.100  # Deploy with a specific version
#   pnpm run deploy:micros 1.0.101 --hot-swap # Existing running service
#
# Prerequisites:
#   - .deploy.local config file (generated by /vpk-deploy skill)
#   - Docker Desktop running
#   - atlas CLI installed and authenticated
#   - service-descriptor.yml configured
#
# This script automatically handles Docker registry authentication by:
# 1. Granting push permissions via atlas packages permission grant
# 2. Logging into Docker registry with credentials from .deploy.local
# 3. Building and pushing the image
# 4. Deploying to Micros

set -euo pipefail

DEPLOY_LIB=".agents/skills/vpk-deploy/scripts/deploy-lib.sh"
if [ ! -f "$DEPLOY_LIB" ]; then
  echo "❌ Missing deployment helper: $DEPLOY_LIB"
  exit 1
fi
# shellcheck disable=SC1090
source "$DEPLOY_LIB"

# Load configuration from .deploy.local
CONFIG_FILE=".deploy.local"
if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Missing .deploy.local config file"
  echo ""
  echo "This file is generated during your first deployment."
  echo "Run /vpk-deploy to set up deployment configuration."
  echo ""
  exit 1
fi

# Source the config file to load SERVICE_NAME, DOCKER_USERNAME, DOCKER_PASSWORD, ENV
source "$CONFIG_FILE"

# Validate required variables from config
if [ -z "${SERVICE_NAME:-}" ] || [ -z "${DOCKER_USERNAME:-}" ] || [ -z "${DOCKER_PASSWORD:-}" ]; then
  echo "❌ Invalid .deploy.local config"
  echo ""
  echo "Required variables: SERVICE_NAME, DOCKER_USERNAME, DOCKER_PASSWORD"
  echo "Run /vpk-deploy to regenerate the config file."
  echo ""
  exit 1
fi

VERSION=""
ENV="${ENV:-pdev-west2}"  # Use ENV from config or default to pdev-west2
REGISTRY="docker.atl-paas.net"

REQUESTED_MODE=""
RECEIPT_FILE=""
while [ "$#" -gt 0 ]; do
  deploy_arg=$1
  shift
  case "$deploy_arg" in
    --hot-swap|--mode=*)
      if [ -n "$REQUESTED_MODE" ]; then echo "❌ Duplicate or conflicting deployment modes"; exit 2; fi
      if [ "$deploy_arg" = "--hot-swap" ]; then REQUESTED_MODE=hot-swap; else REQUESTED_MODE=${deploy_arg#--mode=}; fi
      vpk_validate_deploy_mode "$REQUESTED_MODE" ;;
    --receipt)
      if [ -n "$RECEIPT_FILE" ] || [ -z "${1:-}" ] || [[ "$1" == --* ]]; then echo "❌ A single receipt path is required"; exit 2; fi
      RECEIPT_FILE=$1
      shift ;;
    --*) echo "❌ Unexpected argument: $deploy_arg"; exit 2 ;;
    *)
      if [ -n "$VERSION" ]; then
        echo "❌ Usage: pnpm run deploy:micros [version] [--mode=cutover|hot-swap] [--receipt path]"
        exit 2
      fi
      VERSION=$deploy_arg ;;
  esac
done
VERSION="${VERSION:-$(vpk_auto_version)}"

case "$ENV" in
  pdev-west2) REGION="us-west-2" ;;
  pdev-apse2) REGION="ap-southeast-2" ;;
  *)
    echo "❌ Unsupported Micros environment: $ENV"
    echo "Supported environments: pdev-west2, pdev-apse2"
    exit 1
    ;;
esac

vpk_validate_service_name "$SERVICE_NAME"
vpk_validate_version "$VERSION"
DEPLOY_MODE=${REQUESTED_MODE:-${VPK_DEPLOY_MODE:-cutover}}
vpk_validate_deploy_mode "$DEPLOY_MODE"
if [ -n "$RECEIPT_FILE" ]; then vpk_verify_receipt "$RECEIPT_FILE"; fi
echo "Deployment mode: $DEPLOY_MODE"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_step() {
  echo ""
  echo -e "${BLUE}📍 $1${NC}"
}

print_success() {
  echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
  echo -e "${RED}❌ $1${NC}"
}

print_warning() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

# Pre-flight checks
print_header "🚀 Pre-Flight Checks"

bash .agents/skills/vpk-deploy/scripts/deploy-check.sh

# Check atlas CLI
print_step "Resolving Atlassian CLI..."
vpk_resolve_atlas
print_success "Atlassian Micros CLI is available"

print_step "Validating service, descriptor, and environment stashes..."
vpk_validate_descriptor_identity "$SERVICE_NAME" service-descriptor.yml
if ! vpk_require_service_and_stashes "$SERVICE_NAME" "$ENV"; then
  exit 1
fi
print_success "Deployment identity and stashes are valid"

print_step "Setting up Docker authentication..."

# Step 1: Grant push permissions via atlas
echo "  → Granting push permissions..."
if "$VPK_ATLAS_BIN" packages permission grant > /dev/null 2>&1; then
  print_success "Push permissions granted"
else
  print_warning "Could not grant permissions (may already be granted)"
fi

# Step 2: Login to Docker registry with embedded credentials
echo "  → Logging into Docker registry..."
if echo "$DOCKER_PASSWORD" | docker login "$REGISTRY" --username "$DOCKER_USERNAME" --password-stdin > /dev/null 2>&1; then
  print_success "Docker authentication successful"
else
  print_error "Docker login failed"
  exit 1
fi

# Deployment
print_header "🚀 Deploying $SERVICE_NAME version $VERSION to $ENV"

# Step 1: Build the static export consumed by backend/Dockerfile
print_step "Step 1/4: Building static export..."
if { [ -n "$RECEIPT_FILE" ] || corepack pnpm run build:export; } && vpk_verify_export "$RECEIPT_FILE"; then
  print_success "Static export built successfully"
else
  print_error "Static export did not produce out/index.html"
  exit 1
fi

# Step 2: Build Docker image
print_step "Step 2/4: Building Docker image..."
if vpk_build_image "$SERVICE_NAME" "$VERSION" "$REGISTRY"; then
  print_success "Docker image built successfully"
else
  print_error "Docker build failed"
  exit 1
fi

# Step 3: Push to registry
print_step "Step 3/4: Pushing Docker image to registry..."
if docker push "$REGISTRY/${SERVICE_NAME}:app-${VERSION}"; then
  print_success "Docker image pushed successfully"
else
  print_error "Docker push failed"
  echo ""
  echo "Troubleshooting tips:"
  echo "  1. Check if API token is still valid at https://packages.atlassian.com/"
  echo "  2. Try running: $VPK_ATLAS_BIN packages permission grant"
  echo "  3. Try manual login: docker logout $REGISTRY && docker login $REGISTRY"
  echo ""
  exit 1
fi

# Step 4: Deploy to Micros
print_step "Step 4/4: Deploying to Micros..."
export VERSION=$VERSION
set -- "--mode=$DEPLOY_MODE"
if "$VPK_ATLAS_BIN" micros service deploy \
  --service=$SERVICE_NAME \
  --env=$ENV \
  --file=service-descriptor.yml "$@"; then
  print_success "Deployment initiated successfully"
else
  print_error "Deployment failed"
  exit 1
fi

# Summary
print_header "✨ Deployment Initiated"

echo ""
echo -e "${GREEN}📍 Service URL:${NC}"
echo "  https://$SERVICE_NAME.$REGION.platdev.atl-paas.net"
echo ""
echo -e "${GREEN}🔍 Monitor deployment:${NC}"
echo "  $VPK_ATLAS_BIN micros service show --service=$SERVICE_NAME --env=$ENV"
echo "  $VPK_ATLAS_BIN micros events -s $SERVICE_NAME -e $ENV -d <deployment-id>"
echo "  For hot swap, confirm the expected version and UPDATE_COMPLETE; events may show the original creation."
echo ""
echo -e "${GREEN}🏥 Health check:${NC}"
echo "  curl https://$SERVICE_NAME.$REGION.platdev.atl-paas.net/api/health"
echo ""
echo -e "${GREEN}📊 View logs:${NC}"
echo "  https://go.atlassian.com/logs/$ENV/$SERVICE_NAME"
echo ""
echo -e "${GREEN}🎯 Requested version: $VERSION${NC}"
echo ""

print_success "Deployment started; follow Micros events until the stack reaches a final state"
echo ""
